# Generated by Django 5.2.7 on 2025-10-23 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tabungan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_cabang', models.CharField(max_length=100)),
                ('nama_uker', models.CharField(max_length=100)),
                ('segmentasi', models.CharField(blank=True, max_length=100, null=True)),
                ('jenis_produk', models.CharField(blank=True, max_length=100, null=True)),
                ('group_product', models.CharField(blank=True, max_length=100, null=True)),
                ('tanggal_posisi', models.DateField(blank=True, null=True)),
                ('flag_posisi', models.CharField(blank=True, max_length=50, null=True)),
                ('nama_region', models.CharField(blank=True, max_length=100, null=True)),
                ('segmentasi_bpr', models.CharField(blank=True, max_length=100, null=True)),
                ('jumlah_rekening', models.IntegerField(blank=True, null=True)),
                ('saldo', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
            ],
        ),
    ]
